server:
  port: 9239
  servlet:
    context-path: /auth


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.122.65:3306/xc_user?characterEncoding=utf-8
    username: root
    password: 263385aA+


redis:
  database: 0
  host: localhost
  port: 6379

