server:
  port: 8849
  servlet:
    context-path: /auth2Res

spring:
  datasource:
    druid:
      url: jdbc:mysql://39.105.122.65:3306/auth_center?characterEncoding=utf-8
      username: root
      password: 263385aA+
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）


mybatis:
  mapper-locations: classpath*:/mapper/*.xml

security:
  oauth2:
    client:
      client-id: overun
      client-secret: overun
      access-token-uri: http://localhost:8848/auth2/oauth/token
      user-authorization-uri: http://localhost:8848/auth2/oauth/authorize
    resource:
      token-info-uri: http://localhost:8848/auth2/oauth/check_token

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
